import './globals.css'
import {ClusterProvider} from '@/components/cluster/cluster-data-access'
import {SolanaProvider} from '@/components/solana/solana-provider'
import {UiLayout} from '@/components/ui/ui-layout'
import {ReactQueryProvider} from './react-query-provider'
import Header from '@/components/ui/Header'
import Footer from '@/components/ui/Footer'
import { WalletProvider } from '@solana/wallet-adapter-react';
import { ConnectionProvider } from '@solana/wallet-adapter-react';
import { PhantomWalletAdapter } from '@solana/wallet-adapter-wallets';

export const metadata = {
  title: 'MULTISLOT',
  description: 'Generated by create-solana-dapp',
}
const wallets = [new PhantomWalletAdapter()];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
         
      <body>
   


        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
            <Header/>
      
          
              <div className={`h-24 bg-black`}></div>
         {children}
         <Footer/>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>

      </body>
    </html>
  )
}
